name: Test

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        animal: [cat, dog, bird]
        config:
          - name: alex
            color: blue
          - name: alex
            color: red
          - name: bob
            color: orange
        

    steps:
      - run: echo animal - ${{ matrix.animal }}, color - ${{ matrix.config.color }}, name - ${{ matrix.config.name }}